image:
  file: .gitpod.dockerfile

tasks:
 - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
 - init: npm install -g nodemon
 - command: nodemon index.js

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - ms-toolsai.jupyter
    - eventyret.bootstrap-4-cdn-snippet
    - formulahendry.auto-close-tag
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-python.python